name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

env:
  APP_DIR: /opt/abcp_b24_sync

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show workspace tree (debug)
        run: |
          pwd
          ls -la
          echo "-----"
          find . -maxdepth 2 -type f -print | sort

      - name: Upload files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT != '' && secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: ./              # копируем весь репозиторий
          target: ${{ env.APP_DIR }}
          overwrite: true
          rm: true

      - name: Configure & start systemd service on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT != '' && secrets.VPS_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -euo pipefail

            APP_DIR="${{ env.APP_DIR }}"
            echo "Deploy dir: $APP_DIR"
            sudo mkdir -p "$APP_DIR"
            sudo chown -R "$USER":"$USER" "$APP_DIR"
            cd "$APP_DIR"

            echo "[deps] Installing python/venv/pip if missing..."
            if command -v apt-get >/dev/null 2>&1; then
              sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-venv python3-pip
            elif command -v dnf >/dev/null 2>&1; then
              sudo dnf install -y python3 python3-pip
            elif command -v yum >/dev/null 2>&1; then
              sudo yum install -y python3 python3-pip
            elif command -v apk >/dev/null 2>&1; then
              sudo apk add --no-cache python3 py3-pip
            fi

            # каталоги
            mkdir -p data logs scripts var

            # venv + зависимости (с фолбэком на virtualenv)
            if [ ! -x .venv/bin/python ]; then
              if ! python3 -m venv .venv 2>/dev/null; then
                python3 -m pip install --user virtualenv
                python3 -m virtualenv .venv
              fi
            fi
            . .venv/bin/activate
            python -V
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt

            # убедимся, что сервисный скрипт исполняемый
            chmod +x scripts/run_service.sh

            # systemd unit (ВАЖНО: без кавычек у heredoc — подставит ${APP_DIR})
            sudo tee /etc/systemd/system/abcp-b24-sync.service >/dev/null <<UNIT
            [Unit]
            Description=ABCP -> Bitrix24 users sync service
            After=network-online.target
            Wants=network-online.target

            [Service]
            Type=simple
            WorkingDirectory=${APP_DIR}
            ExecStart=/bin/bash ${APP_DIR}/scripts/run_service.sh
            Restart=always
            RestartSec=10
            Environment=PYTHONUNBUFFERED=1

            [Install]
            WantedBy=multi-user.target
            UNIT

            sudo systemctl daemon-reload
            sudo systemctl enable abcp-b24-sync.service || true
            sudo systemctl restart abcp-b24-sync.service
            sudo systemctl status --no-pager abcp-b24-sync.service || true
